# Generated by Django 6.0.7 on 2026-08-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordresetotp',
            name='users_passw_user_id_a0ba5f_idx',
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
