# Generated by Django 6.0.7 on 2026-07-31 09:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('pain_level', models.IntegerField(help_text='Pain Level from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('recommended_department', models.CharField(max_length=50)),
                ('score', models.FloatField(blank=True, help_text='Final decision score of the top doctor', null=True)),
                ('confidence', models.IntegerField(blank=True, help_text='Department-match confidence (0-100)', null=True)),
                ('reason', models.TextField(blank=True, help_text='Human-readable explanation of the recommendation', null=True)),
                ('recommendation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_history', to='patients.patient')),
                ('recommended_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='doctors.doctor')),
            ],
            options={
                'indexes': [models.Index(fields=['-recommendation_date'], name='recommendat_recomme_7851e2_idx'), models.Index(fields=['patient', '-recommendation_date'], name='recommendat_patient_89967b_idx'), models.Index(fields=['recommended_department', '-recommendation_date'], name='recommendat_recomme_4f275c_idx')],
            },
        ),
    ]
