# Generated by Django 6.0.7 on 2026-08-05 09:41

import apps.lab_reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lab_reports/', validators=[apps.lab_reports.models.validate_lab_report_file])),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('ocr_text', models.TextField(blank=True)),
                ('detected_count', models.PositiveSmallIntegerField(default=0)),
                ('updated_count', models.PositiveSmallIntegerField(default=0)),
                ('unchanged_count', models.PositiveSmallIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lab_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReportField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('patient_field', models.CharField(blank=True, max_length=100)),
                ('extracted_value', models.CharField(max_length=255)),
                ('previous_value', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('change_status', models.CharField(choices=[('INSERTED', 'Inserted'), ('UPDATED', 'Updated'), ('UNCHANGED', 'Unchanged')], default='UNCHANGED', max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='lab_reports.labreport')),
            ],
            options={
                'ordering': ['field_name'],
            },
        ),
    ]
