# Generated by Django 6.0.7 on 2026-10-01 14:57

import apps.lab_reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='file',
            field=models.FileField(upload_to=apps.lab_reports.models.lab_report_upload_path, validators=[apps.lab_reports.models.validate_lab_report_file]),
        ),
        migrations.AlterField(
            model_name='labreportfield',
            name='change_status',
            field=models.CharField(choices=[('INSERTED', 'Inserted'), ('UPDATED', 'Updated'), ('UNCHANGED', 'Unchanged'), ('SKIPPED', 'Needs review (not saved)')], default='UNCHANGED', max_length=10),
        ),
    ]
