# Generated by Django 6.0.7 on 2026-10-01 17:36

import apps.lab_reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_reports', '0002_alter_labreport_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreport',
            name='ocr_text',
        ),
        migrations.AddField(
            model_name='labreport',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_lab_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labreport',
            name='identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labreport',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labreport',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labreportfield',
            name='converted_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='labreportfield',
            name='converted_value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='labreportfield',
            name='skip_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='file',
            field=models.FileField(storage=apps.lab_reports.models.lab_report_storage, upload_to=apps.lab_reports.models.lab_report_upload_path, validators=[apps.lab_reports.models.validate_lab_report_file]),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('AWAITING', 'Awaiting confirmation'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12),
        ),
    ]
