# Generated by Django 6.0.7 on 2026-10-03 06:35

import apps.lab_reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_reports', '0003_preview_identity_encryption'),
        ('patients', '0004_patient_bilirubin_total_patient_blood_urea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=32)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('report_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-report_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='labreport',
            name='extracted_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='labreport',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='labreport',
            name='ocr_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='review_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='labreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lab_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labreportfield',
            name='flag',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='file',
            field=models.FileField(blank=True, storage=apps.lab_reports.models.lab_report_storage, upload_to=apps.lab_reports.models.lab_report_upload_path, validators=[apps.lab_reports.models.validate_lab_report_file]),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PENDING_CONFIRMATION', 'Awaiting confirmation'), ('NEEDS_REVIEW', 'Needs review'), ('REJECTED', 'Rejected'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=24),
        ),
        migrations.AlterField(
            model_name='labreportfield',
            name='change_status',
            field=models.CharField(choices=[('INSERTED', 'Inserted'), ('UPDATED', 'Updated'), ('UNCHANGED', 'Unchanged'), ('SKIPPED', 'Needs review (not saved)'), ('HISTORY', 'Saved to history')], default='UNCHANGED', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='labreport',
            constraint=models.UniqueConstraint(condition=models.Q(('file_hash', ''), _negated=True), fields=('patient', 'file_hash'), name='unique_lab_report_file_per_patient'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab_reports.labreport'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['patient', 'test_name', 'report_date'], name='labresult_patient_test_date'),
        ),
    ]
