# Generated by Django 6.0.7 on 2026-10-03 17:46

from datetime import date

from django.conf import settings
from django.db import migrations, models


def backfill_report_date(apps, schema_editor):
    """Fill an empty report_date from the date stored with the extraction, if any.
    Rows with no stored date stay empty (the date ordering check ignores them)."""
    LabReport = apps.get_model('lab_reports', 'LabReport')
    for report in LabReport.objects.filter(report_date__isnull=True).only('id', 'extracted_json'):
        raw = (report.extracted_json or {}).get('report_date') if isinstance(report.extracted_json, dict) else None
        try:
            value = date.fromisoformat(raw) if raw else None
        except (TypeError, ValueError):
            value = None
        if value:
            LabReport.objects.filter(pk=report.pk).update(report_date=value)


class Migration(migrations.Migration):

    dependencies = [
        ('lab_reports', '0005_status_values_and_result_history'),
        ('patients', '0005_patient_id_typed_by_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='report_date_source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='labreport',
            name='report_date_user_entered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['patient', 'report_date'], name='labreport_patient_date'),
        ),
        migrations.RunPython(backfill_report_date, migrations.RunPython.noop),
    ]
