# Generated by Django 6.0.7 on 2026-10-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_reports', '0006_report_date_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PENDING_CONFIRMATION', 'Awaiting confirmation'), ('NEEDS_REVIEW', 'Needs review'), ('REJECTED', 'Rejected'), ('CONFIRMED', 'Confirmed'), ('NO_VALUES_SAVEABLE', 'No values; can be saved as a document'), ('SAVED_NO_VALUES', 'Saved without card values'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=24),
        ),
    ]
