# Generated by Django 6.0.7 on 2026-08-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='e.g. 120/80 mmHg', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_sugar_fasting',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fasting blood sugar mg/dL', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_sugar_random',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Random blood sugar mg/dL', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cholesterol_hdl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='HDL cholesterol mg/dL', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cholesterol_ldl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='LDL cholesterol mg/dL', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cholesterol_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cholesterol mg/dL', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hemoglobin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hemoglobin g/dL', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='triglycerides',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Triglycerides mg/dL', max_digits=6, null=True),
        ),
    ]
