# Generated by Django 6.0.7 on 2026-08-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_add_clinical_vitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bilirubin_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total bilirubin mg/dL', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_urea',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Blood urea mg/dL', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='esr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ESR mm/hr', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hba1c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='HbA1c %', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Heart rate in bpm', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hematocrit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hematocrit %', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='platelet_count',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platelet count', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='potassium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Potassium mEq/L', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rbc_count',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RBC count', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='serum_creatinine',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Serum creatinine mg/dL', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sodium mEq/L', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='spo2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='SpO2 percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ssgot_ast',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='SGOT/AST U/L', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ssgpt_alt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='SGPT/ALT U/L', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='t3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='T3 ng/dL', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='t4',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='T4 μg/dL', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tsh',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='TSH mIU/L', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='uric_acid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Uric acid mg/dL', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='wbc_count',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='WBC count', max_digits=6, null=True),
        ),
    ]
