# Generated by Django 6.0.7 on 2026-10-03 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_bilirubin_total_patient_blood_urea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(db_index=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^PAT-[A-Z0-9]{4,12}$', 'Patient ID must be PAT- followed by 4 to 12 capital letters or digits, e.g. PAT-9C0E059C.')]),
        ),
    ]
