# Generated by Django 6.0.7 on 2026-07-31 09:10

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='patient_documents/', validators=[apps.documents.models.validate_file_extension_and_size])),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('MEDICAL', 'Medical Report'), ('ADDITIONAL', 'Additional Report')], default='ADDITIONAL', max_length=10)),
            ],
        ),
    ]
