# Generated by Django 6.0.7 on 2026-10-01 14:57

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[apps.documents.models.validate_file_extension_and_size]),
        ),
    ]
