# Generated by Django 6.0.7 on 2026-07-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], db_index=True, default='PENDING', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(db_index=True, editable=False, max_length=15, unique=True)),
                ('uuid_token', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(choices=[('General Medicine', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology'), ('Orthopedics', 'Orthopedics'), ('ENT', 'ENT'), ('Ophthalmology', 'Ophthalmology'), ('Psychiatry', 'Psychiatry'), ('Oncology', 'Oncology'), ('Urology', 'Urology'), ('Gastroenterology', 'Gastroenterology'), ('Nephrology', 'Nephrology'), ('Endocrinology', 'Endocrinology'), ('Pulmonology', 'Pulmonology'), ('Emergency Medicine', 'Emergency Medicine'), ('Family Medicine', 'Family Medicine'), ('Dentistry', 'Dentistry'), ('Radiology', 'Radiology'), ('Pathology', 'Pathology')], max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctor_photos/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('availability_schedule', models.JSONField(default=dict, help_text="e.g. {'Monday': '09:00-17:00', 'Tuesday': '09:00-17:00'}")),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('medications', models.TextField(help_text='List of prescribed medicines with dosage')),
                ('notes', models.TextField(blank=True, null=True)),
                ('prescription_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-prescription_date'],
            },
        ),
    ]
